dist: trusty
sudo: false

language: python
cache:
  - pip
  - yarn

services:
  - mysql
  - postgresql

before_install:
  - psql -c 'create database olapy_test;' -U postgres
  - mysql -e 'create database olapy_test;'

install:
  - pip install -U pip setuptools tox tox-travis wheel

env:
#  matrix:
  global:
    - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://postgres@localhost/olapy_test
    - SQLALCHEMY_DATABASE_URI=mysql://travis@localhost/olapy_test
    - SQLALCHEMY_DATABASE_URI=sqlite://
  matrix:
    include:
      - python: 2.7
        env: TOXENV=py27
      - python: 3.6
        env: TOXENV=py36
      - python: 2.7
        env: TOX

#matrix:
#  include:
#    - python: 2.7
#      env: TOXENV=py27-postgres
#    - python: 2.7
#      env: TOXENV=py27-mysql
#    - python: 2.7
#      env: TOXENV=py27-sqlite
#    - python: 3.6
#      env: TOXENV=py36-postgres
#    - python: 3.6
#      env: TOXENV=py36-mysql
#    - python: 3.6
#      env: TOXENV=py36-sqlite
#    - python: 2.7
#      env: TOXENV=lint

#matrix:
#  include:
#    - python: 2.7
#      env: TOXENV=py27
#    - python: 3.6
#      env: TOXENV=py36
#    - python: 2.7
#      env: TOXENV=lint

script:
  - tox

notifications:
  slack:
    rooms:
      - abilian:dTtRD7DHS4Dw3jfRrqytQWU6#code
    on_success: change
    on_failure: always
