sudo: required
dist: trusty
# group: deprecated-2017Q3

language: python
cache: pip

services:
  - mysql
  - postgresql

before_install:
  # Setup Postgres
  - psql -c 'create database sales_test;' -U postgres
  # Setup Mysql
  - mysql -e 'CREATE DATABASE IF NOT EXISTS sales_test;'
  - mysql -u root -e "CREATE USER 'root_db'@'localhost' IDENTIFIED BY 'toor';"
  - mysql -u root -e "GRANT ALL ON sales_test.* TO 'root_db'@'localhost';"

install:
  - pip install -U pip setuptools tox tox-travis wheel

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-postgres
    - python: 2.7
      env: TOXENV=py27-mysql
    - python: 2.7
      env: TOXENV=py27-sqlite
    - python: 3.6
      env: TOXENV=py36-postgres
    - python: 3.6
      env: TOXENV=py36-mysql
    - python: 3.6
      env: TOXENV=py36-sqlite
    - python: 2.7
      env: TOXENV=lint

script:
  - tox

notifications:
  slack:
    rooms:
      - abilian:dTtRD7DHS4Dw3jfRrqytQWU6#code
    on_success: change
    on_failure: always
