dist: trusty
sudo: false
# group: deprecated-2017Q3

language: python
cache: pip

services:
  - mysql
  - postgresql

before_install:
  - psql -c 'create database olapy_test;' -U postgres
  - mysql -e 'create database olapy_test;'

install:
  - pip install -U pip setuptools tox tox-travis wheel

env:
  global:
    - POSTGRES_URI=postgresql+psycopg2://postgres@localhost/olapy_test
    - MYSQL_URI=mysql://travis@localhost/olapy_test

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-postgres
    - python: 2.7
      env: TOXENV=py27-mysql
    - python: 2.7
      env: TOXENV=py27-sqlite
    - python: 3.6
      env: TOXENV=py36-postgres
    - python: 3.6
      env: TOXENV=py36-mysql
    - python: 3.6
      env: TOXENV=py36-sqlite
    - python: 2.7
      env: TOXENV=lint

script:
  - tox

notifications:
  slack:
    rooms:
      - abilian:dTtRD7DHS4Dw3jfRrqytQWU6#code
    on_success: change
    on_failure: always
