package:
  name: olapy
  version: 'ec03b9f3c2b9ca6802dc34491c42ad4e61f689c9'

source:
  url: https://github.com/abilian/olapy/archive/ec03b9f3c2b9ca6802dc34491c42ad4e61f689c9.zip

  patches:
    - patches/remove_unuseful_libs_(spyne-sqlalchemy-click-pyyaml).patch


requirements:
  run:
    - pandas
    - xmlwitch
    - attrs
    - regex

test:
  imports:
    - olapy
