name: Install and run Python tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies 1
      run: |
        which pip
    - name: Install dependencies 2
      run: |
        pip freeze
    - name: Install dependencies 3
      run: |
        pip install --upgrade pip setuptools
        pip freeze
        pip install pandas==0.24.2
        pip freeze
        pip install -r requirements.txt
        pip freeze
        pip install -r dev-requirements.txt
        pip freeze
        pip install .
        pip freeze
    - name: Test with pytest
      run: |
        pytest
